### ISSUE TITLE
connect the owner's mailer in an after-create mode (welcome message).

### ISSUE THREAD

**Issue by Laurent-Gi** [the-hacking-team/happy-minute#11] opened 2020-09-05 20:32 UTC
create an Owner Mailer, and generate a cool html message for welcoming the owner.

**Comment by mvoland** [comment] 2020-09-07 18:51
In PR #14 Owner after_create was intended as just a test, the email is basically empty. Should this issue be closed by this PR ? There should be an other Issue regarding mails anyway right? @Laurent-Gi

**Closed** 2020-09-07 20:48 UTC
Labels: enhancement
